# Generated by Django 4.2.7 on 2025-04-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('valuer', '0001_initial'),
        ('broker', '0001_initial'),
        ('product', '0001_initial'),
        ('authentication', '0001_initial'),
        ('qs', '0001_initial'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='broker.broker'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='product.product'),
        ),
        migrations.AddField(
            model_name='application',
            name='qs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='qs.qs'),
        ),
        migrations.AddField(
            model_name='application',
            name='valuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='valuer.valuer'),
        ),
    ]
