from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ApplicationViewSet, NoteViewSet

router = DefaultRouter()
router.register(r'applications', ApplicationViewSet)
router.register(r'notes', NoteViewSet)

urlpatterns = [
    path('', include(router.urls)),
    # The following URLs are automatically generated by the router:
    # /applications/{id}/submit/
    # /applications/{id}/review/
    # /applications/{id}/generate-documents/
    # /applications/{id}/finalize/
]
