# Generated by Django 4.2.7 on 2025-04-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('loan_type', models.CharField(max_length=50)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_term_months', models.IntegerField()),
                ('max_term_months', models.IntegerField()),
                ('establishment_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='product.product')),
            ],
        ),
    ]
