# Generated by Django 4.2.7 on 2025-04-16 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('id_number', models.CharField(max_length=50)),
                ('id_type', models.CharField(max_length=50)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-Employed'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired')], max_length=20)),
                ('employer', models.CharField(blank=True, max_length=255, null=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerMergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_borrower_data', models.JSONField()),
                ('merged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('primary_borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_merge_records', to='borrower.borrower')),
            ],
        ),
    ]
